const FIRE_PROJECTILE = "FIRE_PROJECTILE"
const MOVE_ONE_FORWARD = "MOVE_ONE_FORWARD"
const REMOVE_PROJECTILE = "REMOVE_PROJECTILE"
const REMOVE_PROJECTILES_ON_LEAVE = "REMOVE_PROJECTILES_ON_LEAVE"

module.exports = {
    FIRE_PROJECTILE,
    MOVE_ONE_FORWARD,
    REMOVE_PROJECTILE,
    REMOVE_PROJECTILES_ON_LEAVE,
}