const ADD_OR_UPDATE_PLAYER = "ADD_OR_UPDATE_PLAYER"
const REMOVE_PLAYER = "REMOVE_PLAYER"
const INCREMENT_COUNTER = "INCREMENT_COUNTER"
const UPDATE_WALK_TIME = "UPDATE_WALK_TIME"
const UPDATE_FIRE_TIME = "UPDATE_FIRE_TIME"
const ADD_ROTATION = "ADD_ROTATION"
const WALK_AWAY_FROM_WALL = "WALK_AWAY_FROM_WALL"
const WALK_FORWARD = "WALK_FORWARD"
const WALK_BACKWARD = "WALK_BACKWARD"
const DECREASE_HEALTH = "DECREASE_HEALTH"
const SET_ROTATION = "SET_ROTATION"
const WALK_FOLLOW_SPEED = "WALK_FOLLOW_SPEED"
const SET_USERNAME = "SET_USERNAME"

module.exports = {
    ADD_OR_UPDATE_PLAYER,
    REMOVE_PLAYER,
    INCREMENT_COUNTER,
    UPDATE_WALK_TIME,
    UPDATE_FIRE_TIME,
    ADD_ROTATION,
    WALK_AWAY_FROM_WALL,
    WALK_FORWARD,
    WALK_BACKWARD,
    DECREASE_HEALTH,
    SET_ROTATION,
    WALK_FOLLOW_SPEED,
    SET_USERNAME
}